<?php
/**
 * System generated by SysGen (System Generator with Formdin Framework) 
 * Download SysGen: https://github.com/bjverde/sysgen
 * Download Formdin Framework: https://github.com/bjverde/formDin
 * 
 * SysGen  Version: 1.3.1-alpha
 * FormDin Version: 4.4.3-alpha
 * 
 * System xx created in: 2019-04-11 00:32:52
 */
class MockFieldsOnSelectedTableVO
{
    private $column_name = null;
    private $required = null;
    private $data_type = null;
    private $char_max = null;
    private $num_length = null;
    private $num_scale = null;
    private $column_comment = null;
    private $key_type = null;
    private $autoincrement = null;
    private $column_default = null;
    private $referenced_table_name = null;
    private $referenced_column_name = null;
    private $table_schema = null;
    private $table_name = null;
    private $table_catalog = null;        
    
    public function __construct( $column_name=null
                                , $required = null
                                , $data_type = null
                                , $char_max = null
                                , $num_length = null
                                , $num_scale = null
                                , $column_comment = null
                                , $key_type = null
                                , $autoincrement = null
                                , $column_default = null
                                , $referenced_table_name = null
                                , $referenced_column_name = null
                                , $table_schema = null
                                , $table_name = null
                                , $table_catalog = null
                                )
    {
        $this->setColumn_name( $column_name );
        $this->setRequired( $required );
        $this->setData_type( $data_type );
        $this->setChar_max( $char_max );
        $this->setNum_length( $num_length );
        $this->setNum_scale(  $num_scale );
        $this->setColumn_comment( $column_comment );
        $this->setKey_type( $key_type );
        $this->setAutoincrement($autoincrement);
        $this->setColumn_default($column_default);
        $this->setReferenced_table_name($referenced_table_name);
        $this->setReferenced_column_name($referenced_column_name);
        $this->setTable_schema($table_schema);
        $this->setTable_name($table_name);
        $this->setTable_catalog($table_catalog);
    }

    public function getColumn_name()
    {
        return $this->column_name;
    }    
    public function setColumn_name($column_name)
    {
        $this->column_name = $column_name;
    }
    
    public function getRequired()
    {
        return $this->required;
    }
    public function setRequired($required)
    {
        $this->required = $required;
    }

    public function getData_type()
    {
        return $this->data_type;
    }
    public function setData_type($data_type)
    {
        $this->data_type = $data_type;
    }
    
    public function getChar_max()
    {
        return $this->char_max;
    }
    public function setChar_max($char_max)
    {
        $this->char_max = $char_max;
    }
    
    public function getNum_length()
    {
        return $this->num_length;
    }
    public function setNum_length($num_length)
    {
        $this->num_length = $num_length;
    }
    
    public function getNum_scale()
    {
        return $this->num_scale;
    }
    public function setNum_scale($num_scale)
    {
        $this->num_scale = $num_scale;
    }
    
    public function getColumn_comment()
    {
        return $this->column_comment;
    }
    public function setColumn_comment($column_comment)
    {
        $this->column_comment = $column_comment;
    }
    
    public function getKey_type()
    {
        return $this->key_type;
    }
    public function setKey_type($key_type)
    {
        $this->key_type = $key_type;
    }
    
    public function getAutoincrement()
    {
        return $this->autoincrement;
    }
    public function setAutoincrement($autoincrement)
    {
        $this->autoincrement = $autoincrement;
    }
    
    public function getColumn_default()
    {
        return $this->column_default;
    }
    public function setColumn_default($column_default)
    {
        $this->column_default = $column_default;
    }
    
    public function getReferenced_table_name()
    {
        return $this->referenced_table_name;
    }
    public function setReferenced_table_name($referenced_table_name)
    {
        $this->referenced_table_name = $referenced_table_name;
    }
    
    public function getReferenced_column_name()
    {
        return $this->referenced_column_name;
    }
    public function setReferenced_column_name($referenced_column_name)
    {
        $this->referenced_column_name = $referenced_column_name;
    }
    
    public function getTable_schema()
    {
        return $this->table_schema;
    }
    public function setTable_schema($table_schema)
    {
        $this->table_schema = $table_schema;
    }
    
    public function getTable_name()
    {
        return $this->table_name;
    }
    public function setTable_name($table_name)
    {
        $this->table_name = $table_name;
    }
    
    public function getTable_catalog()
    {
        return $this->table_catalog;
    }
    public function setTable_catalog($table_catalog)
    {
        $this->table_catalog = $table_catalog;
    }
}
?>